name: inspector
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

   # DI
  provider: ^6.0.3

  # State Management
  elementary: ^1.3.1
  bloc: ^8.0.3

  # Network
  chopper: ^4.0.6
  dio: ^4.0.6
  url_launcher: ^6.1.2

  # Database
  flutter_secure_storage: ^6.0.0

  # Models
  dart_mappable: ^1.1.2

  # Flavors
  flutter_dotenv: ^5.0.2

  # Navigation
  auto_route: ^5.0.1


  # UI
  pinput: ^2.2.11
  cupertino_icons: ^1.0.2
  flutter_svg:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  google_fonts: ^3.0.1
  infinite_scroll_pagination: ^3.2.0
  expandable_text: ^2.3.0
  image_crop:
    git:
      url: https://github.com/meg4cyberc4t/image_crop
      ref: master
  time_picker_sheet:
    git:
      url: https://github.com/GDTuka/time-picker-sheet
      ref: master

  # Utils
  jiffy: ^5.0.0
  logger: ^1.1.0
  equatable: ^2.0.5
  mask_text_input_formatter: ^2.3.0
  image_picker: 0.8.5+3 
  photo_manager: ^2.1.4
  gallery_saver: ^2.3.2
  open_file: ^3.2.1

  flutter_contacts: ^1.1.5

  # I18n
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  file_picker: ^4.6.1
  easy_debounce: ^2.0.2+1
  flutter_bloc: ^8.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  flutter_gen_runner:
  chopper_generator:
  json_serializable:
  auto_route_generator:
  dart_mappable_builder: ^1.1.3
  elementary_test: ^1.1.2
  mocktail: ^0.3.0

 

flutter_gen:
  output: lib/generated/
  style: camel-case
  integrations:
    flutter_svg: true


flutter:


  uses-material-design: true

